apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: istiod
      version: "1.26.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
  values:
    global:
      hub: docker.io/istio
      tag: 1.26.1
      proxy:
        autoInject: enabled
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true
    meshConfig:
      enablePrometheusMerge: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: "1.26.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
  values:
    service:
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        targetPort: 80
      - name: https
        port: 443
        targetPort: 443
    labels:
      app: istio-gateway
      istio: gateway
