apiVersion: v1
kind: Service
metadata:
  name: traefik-lb
  namespace: internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-k3s
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "4.194.122.145"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP