apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crd
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "1.9.0-rc1"
  values:
    gatewayAPI: true
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: traefik
#   namespace: internal
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: traefik
#       sourceRef:
#         kind: HelmRepository
#         name: traefik
#         namespace: flux-system
#       version: "34.4.0"
#   values:
#     ingressRoute:
#       dashboard:
#         enabled: true
#     service:
#       type: LoadBalancer
#       spec:
#         externalTrafficPolicy: Local
#       additionalServices:
#         internal:
#           type: ClusterIP
#     ports:
#       traefik:
#         expose:
#           default: false
#           internal: true
#       postgres:
#         port: 5432
#         expose:
#           default: true
#         exposedPort: 5432
#         protocol: TCP
#       mysql:
#         port: 3306
#         expose:
#           default: true
#         exposedPort: 3306
#         protocol: TCP
#     logs:
#       access:
#         enabled: true
#         format: json
#         bufferingSize: 100
#         fields:
#           general:
#             names:
#               defaultmode: keep
#           headers:
#             names:
#               User-Agent: keep
#               Referer: keep