apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      version: "5.8.58"
  values:
    controller:
      disableRememberMe: true
      numExecutors: 2
      executorMode: "NORMAL"
      admin:
        username: admin
        password: admin
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - jenkins.wush.site