apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crd
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-crds
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "1.4.0"
  values:
    gatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: internal
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "34.4.0"
  values:
    experimental:
      plugins:
        traefik-middleware-request-logger:
          moduleName: "github.com/cookielab/traefik-middleware-request-logger"
          version: "v0.0.9"
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--api.insecure=true"
      - "--experimental.plugins.traefik-middleware-request-logger.modulename=github.com/cookielab/traefik-middleware-request-logger"
      - "--experimental.plugins.traefik-middleware-request-logger.version=v0.0.9"
    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
      additionalServices:
        internal:
          type: ClusterIP
    ports:
      traefik:
        expose:
          default: false
          internal: true
      postgres:
        port: 5432
        expose:
          default: true
        exposedPort: 5432
        protocol: TCP
      mysql:
        port: 3306
        expose:
          default: true
        exposedPort: 3306
        protocol: TCP
    logs:
      access:
        enabled: true
        format: json
        bufferingSize: 100
        fields:
          general:
            names:
              defaultmode: keep
          headers:
            names:
              User-Agent: keep
              Referer: keep
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth-secret
  namespace: internal
type: kubernetes.io/basic-auth
stringData:
  username: test
  password: test
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
  namespace: internal
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: request-logger
  namespace: internal
spec:
  plugin:
    traefik-middleware-request-logger:
      ContentTypes:
        - application/json
        - application/x-www-form-urlencoded
        - text/html
      Limits:
        MaxBodySize: "20971520"
      RequestIDHeaderName: X-Request-ID
      IncludeHeaders:
        - X-Forwarded-For
        - X-Real-IP
      SkipHeaders:
        - Authorization
      StatusCodes:
        - 200
      LogTarget: stdout